#ifndef COLLECTIONS_H
#define COLLECTIONS_H

enum ControllerState {
    TRIGGERED_A_STATE,
    TRIGGERED_B_STATE,
    TRIGGERED_FROM_A_TO_B_STATE,
    TRIGGERED_FROM_B_TO_A_STATE,
    TRIGGERED_STATE,
    ACTIVE_STATE,
    FREED_A_STATE,
    FREED_B_STATE,
    FREED_FROM_A_TO_B_STATE,
    FREED_FROM_B_TO_A_STATE,
    FREED_STATE,
    IDLE_STATE
};

enum AnimationDirection {
    FROM_A_TO_B,
    FROM_B_TO_A
};

#endif //COLLECTIONS_H